### ISSUE TITLE
Convert geospatial data to make it readable in BQ

### ISSUE THREAD

**Issue by galamit86** [dataverbinders/toepol#5]
After the ingestion of the BAG extract into a raw zone, the geospatial data should be converted to a format readable by BQ.

**Comment by MarcZoon** [comment]
Where applicable, the tables now contain a column 'geography' containing the geospatial data in WKT format.

This can be parsed in BQ using the ST_GEOGFROMTEXT function:
`
SELECT
  ST_GEOGFROMTEXT(geometrie.geo_point) as point
FROM
  dataverbinders-dev.bag.Verblijfsobject
`
